[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
jampass = "F1w7fTd2nex3mYFA8sH85kU74dbFy88jKeCMDYDBg7eT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tahliltahlil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
